wole00-sp2 pilot version
nvbach91/4IZ268-2023-2024-ZS pull request #148
Opened 2023-12-12 15:35 UTC by eduardwolf

Link to application: https://eso.vse.cz/~wole00/sp2/

2024-02-01 15:12 UTC, nvbach91 requested changes

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +        let searchType = document.getElementById("searchType").value;
opakovane selektovani elementu

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/index.html
> +                        <form onsubmit="App.handleSubmit(); return false;">
nepouzivat inline javascript

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/index.html
> +                        <a id="addToFav" class="addToFav" href="" onclick="App.addToFav();return false" style="display: none;">Přidat do oblíbených</a>
nepouzivat inline javascript

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/index.html
> +                                <option value="Jmena">Jména</option>
value="by-name"
value="by-date"

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +        return new Promise((resolve, reject) => {
chybi indikace nacitani dat v pozadi

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +    getDate: (name) => { //returns promise with a response containing the date, takes name as argument
fetchDateByName + fetchNameByDate

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +            localStorage.setItem(document.getElementById("nameSpan").textContent, document.getElementById("dateSpan").textContent);
struktura dat v localStorage ma vypadat takto:
```js
{
  holidays: {
    David: '30. 12.',
    Lenka: '21. 2.',
    ...
  }
}
```

a ne tak jak to mate ted

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +                document.getElementById("favDiv").appendChild(div);
opakovane selektovani elementu
zasah do DOM v cyklu

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +        nameSpan = document.getElementById("nameSpan");
deklarace promenne

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +                anchor.setAttribute("onclick", `App.removeFav('${key}');this.parentNode.remove();return false`);
nepouzivat inline javascript

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +                let anchor = document.createElement("a");
proc to neni button?

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +    loadFavorites: (firstTime) => { //load all favorites from local storage
pridejte moznost serazeni teto tabulky podle datumu a podle jmena

2024-02-01 15:12 UTC, nvbach91 commented on www/wole00/sp2/assets/js/script.js
> +            let searchInput = document.getElementById("searchInput").value;
chybi osetrovani vstupu

2024-02-01 18:23 UTC, eduardwolf commented on www/wole00/sp2/assets/js/script.js
> +            let searchInput = document.getElementById("searchInput").value;
Opraveno ve Version 1.1

2024-02-01 18:24 UTC, eduardwolf commented on www/wole00/sp2/assets/js/script.js
> +                anchor.setAttribute("onclick", `App.removeFav('${key}');this.parentNode.remove();return false`);
Opraveno ve Version 1.1

2024-02-01 18:24 UTC, eduardwolf commented on www/wole00/sp2/assets/js/script.js
> +                document.getElementById("favDiv").appendChild(div);
Opraveno ve Version 1.1

2024-02-01 18:24 UTC, eduardwolf commented on www/wole00/sp2/assets/js/script.js
> +    getDate: (name) => { //returns promise with a response containing the date, takes name as argument
Opraveno ve Version 1.1

2024-02-01 18:24 UTC, eduardwolf commented on www/wole00/sp2/index.html
> +                                <option value="Jmena">Jména</option>
Opraveno ve Version 1.1

2024-02-01 18:24 UTC, eduardwolf commented on www/wole00/sp2/index.html
> +                        <a id="addToFav" class="addToFav" href="" onclick="App.addToFav();return false" style="display: none;">Přidat do oblíbených</a>
Opraveno ve Version 1.1

2024-02-01 18:24 UTC, eduardwolf commented on www/wole00/sp2/index.html
> +                        <form onsubmit="App.handleSubmit(); return false;">
Opraveno ve Version 1.1

2024-02-01 18:24 UTC, eduardwolf commented on www/wole00/sp2/assets/js/script.js
> +        let searchType = document.getElementById("searchType").value;
Opraveno ve Version 1.1

2024-02-01 18:52 UTC, eduardwolf commented on www/wole00/sp2/assets/js/script.js
> +        return new Promise((resolve, reject) => {
Opraveno ve Version 1.2

2024-02-01 18:52 UTC, eduardwolf commented on www/wole00/sp2/assets/js/script.js
> +                let anchor = document.createElement("a");
Opraveno ve Version 1.2

2024-02-02 18:26 UTC, nvbach91 approved these changes

2024-02-02 18:27 UTC, merged