hore06-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #155
Opened 2023-12-16 18:01 UTC by horalikova

Dobrý den,
zde odkaz na SP2.

https://eso.vse.cz/~hore06/sp2/

2024-01-18 15:48 UTC, nvbach91 requested changes
nejde nic pocitat

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +const AllDesc = $('<p><strong>If you changed any information in the form, please click on the Calculate All button, in order to get accurate results.</strong></p>');
tady nepouzivame PascalCase

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +var levels = ["Sedentary: little or no exercise",
const?

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +		var weight = localStorage.getItem('weight');
const

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +		var level = 'level_1';
return 'level_1'

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +	if ($(activitySelect).val() == "Sedentary: little or no exercise") {
proč je tady $?

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +	if ($("#radioMale").is(":checked")
vybirame elementy predem jednou, ne za behu a ne opakovane

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +	else if ($(activitySelect).val() == "Exercise 4-5 times/week") {
a proc ty optiony nemaji atribut `value`?

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +const formLabel = $('<label><strong>Before submitting, make sure all inputs fields are filled.</strong></label>')
nemuzu psat do weight, height ani age

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +const BMIOutput = $('<p id=BMIOutput>');
`"`

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/css/style.css
> +    font-size: medium;
`cursor: pointer`

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +
chce to formatovat kod

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +	$.ajax(settings).done(function (response) {
![image](https://github.com/nvbach91/4IZ268-2023-2024-ZS/assets/20724910/24f747a8-6bc6-4a3b-9aae-cbec5889acfc)

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +var data = [{
const?

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +BMIsubmitButton.on('click', (e) => {
`grid.on('submit', ...)` + `preventDefault()`

2024-01-18 15:48 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +leftContainer.append(formLabel, grid, BMIsubmitButton, BMIOutput, IWsubmitButton, idealweightOutput, AllDesc, AllSubmitButton);
bmiSubmitButton uvnitr formulare

2024-01-18 16:05 UTC, horalikova commented on www/hore06/sp2/js/main.js
> +const formLabel = $('<label><strong>Before submitting, make sure all inputs fields are filled.</strong></label>')
Vstup se zadává pomocí šipek v inputovém poli, psaní z klávesnice je schválně zakázáno.

2024-01-18 19:08 UTC, horalikova commented on www/hore06/sp2/js/main.js
> +const formLabel = $('<label><strong>Before submitting, make sure all inputs fields are filled.</strong></label>')
Již je možné vstup i psát.

2024-01-19 21:19 UTC, nvbach91 approved these changes

2024-01-19 21:19 UTC, nvbach91 commented on www/hore06/sp2/js/main.js
> +	var history = JSON.parse(localStorage.getItem('measurmentsHistory')) || [];
```js
JSON.parse(localStorage.getItem('measurmentsHistory') || '[]')
```

2024-01-19 21:20 UTC, merged