vlcj07-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #156
Opened 2023-12-16 18:46 UTC by hiskym

Struktura souborů a složek + prvotní design stránky

2024-01-11 17:02 UTC, nvbach91 commented
Chybí odkaz na aplikaci

2024-01-11 17:05 UTC, hiskym commented
> Chybí odkaz na aplikaci

https://4iz268-sp2-vlcj07.vercel.app/

2024-01-11 17:16 UTC, nvbach91 requested changes

2024-01-12 15:41 UTC, nvbach91 approved these changes

2024-01-12 15:41 UTC, merged