egea00-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #166
Opened 2023-12-17 15:30 UTC by adacine2

SP2: https://eso.vse.cz/~egea00/sp2/

2024-01-18 11:36 UTC, nvbach91 requested changes
Práce není odevzdána

2024-01-18 20:29 UTC, nvbach91 requested changes
ktere soubory mam hodnotit?

2024-01-18 20:29 UTC, nvbach91 commented on www/egea00/sp2/js/api/weatherApi.js
> +    api3000Url: 'http://localhost:3000/openweather/data/2.5/',
aplikace vola na localhost?

2024-01-18 21:11 UTC, adacine2 commented on www/egea00/sp2/js/api/weatherApi.js
> +    api3000Url: 'http://localhost:3000/openweather/data/2.5/',
pracovni varianta, bohuzel jsem odevzdal pozdeji z nemoznosti spravneho nastaveni 3rd party PROXY serveru
-----
snaha o opravu v nasledujicim commitu FINAL SP2

2024-01-18 21:37 UTC, nvbach91 commented
https://github.com/nvbach91/4IZ268-2023-2024-ZS/pull/257

2024-01-18 21:40 UTC, nvbach91 commented
Zkuste tohle https://github.com/nvbach91/cors-proxy, aspon to bezi na internetu

Uz nezakladejte nove Pull Requesty

2024-01-19 21:16 UTC, nvbach91 approved these changes

2024-01-19 21:17 UTC, merged