telo00-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #178
Opened 2023-12-17 20:22 UTC by lesyabb2

link to application:  https://eso.vse.cz/~telo00/sp2/

2024-01-25 19:26 UTC, nvbach91 requested changes
- aplikace neni funkcni
- obsahuje prilis malo funkcionalit
- zpusob psani kodu je zastaraly
- chybi prace s Browser API

2024-01-25 19:26 UTC, nvbach91 commented on www/telo00/sp2/js/main.js
> +            url: 'http://localhost:443/addTask',
tohle ma byt odkaz na externi REST API sluzba treti strany, ne vlastni API

2024-01-25 19:26 UTC, nvbach91 commented on www/telo00/sp2/js/main.js
> +                $('#input').val('');
opakovane selektovani elementu

2024-01-25 19:26 UTC, nvbach91 commented on www/telo00/sp2/js/main.js
> +            alert('Please enter a task');
nepouzivat alert

2024-02-01 15:36 UTC, nvbach91 requested changes

2024-02-01 15:36 UTC, nvbach91 commented on www/telo00/sp2/main.js
> +        const $spinner = $('#loading-spinner');
opakovane vybirani elementu

2024-02-02 15:47 UTC, lesyabb2 commented
automatické řazeni pro úkoly = priorita, datum. potvrzovací okno pro mazaní úkol, udělat na celé okno, udělat input povinny, přidat barvy pro priority, geolokace

2024-02-02 17:49 UTC, nvbach91 approved these changes

2024-02-02 17:49 UTC, merged