adad05-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #183
Opened 2023-12-17 21:38 UTC by danieladam2001

Link na eso-server: https://eso.vse.cz/~adad05/sp2/

2024-01-04 13:40 UTC, nvbach91 requested changes
- pri asynchronnim zavolani na REST API zobrazit spinner napr. pres celou plochu nebo na tlacitku, na kterem uzivatel kliknul
- bylo by dobre ukladat data o pocasi do localstorage podle datumu, aby se neopakovala volani na API, jelikoz je tam omezeni na poctu volani

2024-01-04 13:40 UTC, nvbach91 commented on www/adad05/sp2/index.html
> +                    <div class="newEventForm">
`<form>` + on('submit' ...) v js

2024-01-04 13:40 UTC, nvbach91 commented on www/adad05/sp2/index.html
> +                        <input class="input2" id="input2" type="text" value=""><br>
`value=""` je zbytecne

2024-01-04 13:40 UTC, nvbach91 commented on www/adad05/sp2/index.html
> +                        <input class="input1" id="input1" type="text" value=""><br>
misto `id="input1"` `id="input2"` pouzivat `name="name"` `name="address"` `name="date"` ...

2024-01-04 13:40 UTC, nvbach91 commented on www/adad05/sp2/index.html
> +                        <div class="time">00:00</div>
tohle lepsi generovat v JS v cyklu

2024-01-04 13:40 UTC, nvbach91 commented on www/adad05/sp2/index.html
> +                        <div class="humidity" id="weather0">20°C 47 %</div>
tady nemaji byt zadne hodnoty, ani defaultni

2024-01-04 13:40 UTC, nvbach91 commented on www/adad05/sp2/js/main.js
> +    console.log(data[eventDate.val()].forEach((element) => {
proc je tady console.log?

2024-01-04 13:40 UTC, nvbach91 commented on www/adad05/sp2/js/main.js
> +    weekDataSorted["tuesday"].forEach((item) => {
tady opakujete kod, muzete predelat pomoci cyklu

2024-01-04 13:40 UTC, nvbach91 commented on www/adad05/sp2/js/main.js
> +        if (data[weekDates[1]]) { weekDataSorted["tuesday"] = data[weekDates[1]].sort(compareByStartTime); }
opet opakovani kodu

2024-01-04 13:40 UTC, nvbach91 commented on www/adad05/sp2/js/main.js
> +    if (day === 0) { weather0.text(`${Math.round(weekTemperatures[0][0][0])}°C ${Math.round(weekTemperatures[0][0][1])} %`) }
opět opakování kódu

2024-01-04 14:50 UTC, danieladam2001 commented
Dobrý den pane inženýre,

chtěl jsem se zeptat, jestli mám na chybách, které jste vypsal, pracovat ještě dnes,
nebo jestli se s nimi počítá na zítřejší obhajobu.

Předem děkuji.
S pozdravem,

Daniel Adam

2024-01-04 14:53 UTC, nvbach91 commented
Zdravím, můžete to samozřejmě dělat dnes pokud máte čas - budete to mít o dost snažší na obhajobě.

2024-01-05 14:25 UTC, nvbach91 approved these changes

2024-01-05 14:25 UTC, merged