lubv00-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #184
Opened 2023-12-17 22:03 UTC by luvvviz

Dobrý den, odkaz na aplikaci: https://eso.vse.cz/~lubv00/sp2/

2024-01-04 15:16 UTC, nvbach91 commented
Aplikace ještě nefunguje s Google API?

2024-01-04 15:21 UTC, nvbach91 requested changes
- při mazání jednoho úkolu zeptat se na potvrzení
- defaultní hodnota priority nastavte na medium
- posledni verze kódu neodpovídá verze aplikace na serveru eso

2024-01-05 07:41 UTC, luvvviz commented
Dobrý den, omlouvám se, nepochopila jsem, že novou verzi musím odevzdat i na eso.vse.cz. Nahrála jsem tam novou verzi a měla by fungovat s Google Calendar API. Nová verze nemá prioritu, protože Google Calendar ji nemá.

2024-01-05 11:08 UTC, nvbach91 approved these changes

2024-01-05 11:08 UTC, merged