vanm34-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #191
Opened 2023-12-17 23:23 UTC by Arkinsen

link: https://eso.vse.cz/~vanm34/sp2/

2023-12-18 10:02 UTC, nvbach91 requested changes
neplatná struktura složek v Pull Requestu

2024-02-01 12:22 UTC, nvbach91 commented
- co jste to odevzdal?
- aplikace nefunguje 
![image](https://github.com/nvbach91/4IZ268-2023-2024-ZS/assets/20724910/2c4de7d7-944d-4fed-a49a-aff11f75d5e4)

2024-02-01 12:52 UTC, Arkinsen commented
1. Aplikace se Slim frameworkem
2. Jsme si vědomí, zkoušel jsme opravit a moc se mi zatím nedaří, teď jsem v práci, ale do večera se pokusím zprovoznit. Jinak na localhostu přes composer a xampp, normálně funguje, tak se na ní mezitím můžete podívat takto.

2024-02-01 13:00 UTC, Arkinsen commented
Je to aplikace, co využívá html, css a JavaScript. Je asynchronní a využívá localstorage. PHP je využité pouze pro posílání mailů. A použil jsem ho, protože jsem měl minulý semestr webové aplikace s Vámi, kde jste mě to Vy učil. Kde je přesně problém?

2024-02-01 13:06 UTC, nvbach91 commented
Projekt odevzdejte znovu v novem Pull Requestu bez PHP kodu a uvidite

2024-02-01 13:17 UTC, Arkinsen commented
Dobrá, mohu se jen zeptat jak posílat maily pomocí JavaScriptu? Já upřímně vůbec nevím, že to je možné. Třeba nějaké odkazy na stránky mi stačí, děkuji.

2024-02-01 13:25 UTC, nvbach91 commented
Ten vas PHP backend si klidne hostujte nekde a muzete to brat jako vlastni REST API, ale nebude to predmetem hodnoceni. Takze si zalozte novy Pull Request, kde Vam poskytnu feedback.

2024-02-01 14:08 UTC, Arkinsen commented
Dobrá

2024-02-02 18:22 UTC, closed without merging