klea10-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #212
Opened 2023-12-28 20:53 UTC by klea0810

Link to application: https://eso.vse.cz/~klea10/sp2/

2024-01-11 16:32 UTC, nvbach91 requested changes
odkaz na aplikaci je nefunkční

2024-01-11 16:32 UTC, nvbach91 commented on www/klea10/sp2/src/scripts/scripts.js
> +        var newLocationInput = $('#new-location-input');
opakovane vybirani elementu ze stromu

2024-01-11 16:32 UTC, nvbach91 commented on www/klea10/sp2/src/scripts/scripts.js
> +            $('#new-location').before(newLocationSelector);
opakovane vybirani elementu ze stromu

2024-01-11 16:32 UTC, nvbach91 commented on www/klea10/sp2/src/scripts/scripts.js
> +        $('#search-bar').val('');
opakovane vybirani elementu ze stromu

2024-01-11 16:32 UTC, nvbach91 commented on www/klea10/sp2/src/scripts/scripts.js
> +                var currentDegreesElement = document.getElementById('current-degrees');
pouzit jQuery

2024-01-11 16:35 UTC, nvbach91 requested changes

2024-01-11 16:35 UTC, nvbach91 commented on www/klea10/sp2/public/index.html
> +        <div class="search">
`<form>`

2024-01-11 16:35 UTC, nvbach91 commented on www/klea10/sp2/public/index.html
> +            <div class="new-location" id="new-location">
`<form>`

2024-01-12 13:50 UTC, klea0810 commented on www/klea10/sp2/public/index.html
> +            <button class="search-button" , id="search-button">&#128269;</button>
yOU3QMP9oKmbKdQlXMWG4ad0pFXlvqLn

2024-01-12 13:53 UTC, klea0810 commented on www/klea10/sp2/public/index.html
> +            <button class="search-button" , id="search-button">&#128269;</button>
xnwKsTNEIU9ACggnpZQpyXzh2ZcCIS2k

2024-01-12 15:39 UTC, nvbach91 approved these changes

2024-01-12 15:40 UTC, merged