auza00-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #227
Opened 2024-01-04 15:10 UTC by auzkya

Link: https://eso.vse.cz/~auza00/sp2/

bohužel jsem sem nedokázal nahrát fonty (jsou v aplikaci použity pro říslování mraků), vzhledem k množství soborů (bylo by to více než 100, což nahrát nelze)

2024-01-04 15:59 UTC, nvbach91 requested changes
vytvořte levý panel a zobrazte tam seznam všech existujících míst s tím, že když se na nějaké místo klikne, zvýrazní se na mapě a v rámci klikatelné položky místo smazat

2024-01-04 17:02 UTC, auzkya reviewed
Opraveno:
'cs' v index.html a v main/index.html
jQuery script na spod souboru
javascript v samostatných souborech
nedostatecny kontrast pisma a pozadi

2024-01-05 13:55 UTC, auzkya commented
Vše opraveno + zobrazení v main.html jména/emailu pod kterým je uživatel přihlášen

2024-01-05 14:29 UTC, nvbach91 approved these changes

2024-01-05 14:31 UTC, merged