mald10-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #236
Opened 2024-01-11 02:12 UTC by danvanmalatek

https://eso.vse.cz/~mald10/sp2/

2024-01-11 14:27 UTC, nvbach91 requested changes
- zbytečně se opakovaně volá na endpoint `api_category`
- u true/false odpovedi negenerovat 3. a 4. volby
- hru lze zahájit i bez výběru kritérií?
- jak zastavím nebo zruším aktuální kvíz?

2024-01-11 14:27 UTC, nvbach91 commented on www/mald10/sp2/js/main.js
> +        const queryParams = {
chybi osetreni chybejicich hodnot

2024-01-11 14:27 UTC, nvbach91 commented on www/mald10/sp2/js/main.js
> +<div id="question-number" class="question-number"></div>
zarovnat kod

2024-01-11 14:27 UTC, nvbach91 commented on www/mald10/sp2/js/main.js
> +    $("#category-title").html(question.category);
opekovane vybirani elementu

2024-01-11 14:27 UTC, nvbach91 commented on www/mald10/sp2/js/main.js
> +        date: new Date().toLocaleDateString("en-GB")
`toISOString()`

2024-01-11 15:45 UTC, danvanmalatek commented on www/mald10/sp2/js/main.js
> +    quizContainer.on("click", "#quiz-mute-button", function (event) {
protože tlačítko v době vytváření akce ještě neexistuje (přidá se dynamicky později) a akce mi tedy přímo na tlačítku nefungovala

2024-01-11 15:59 UTC, danvanmalatek commented
> * zbytečně se opakovaně volá na endpoint `api_category`
> * u true/false odpovedi negenerovat 3. a 4. volby
> * hru lze zahájit i bez výběru kritérií?
> * jak zastavím nebo zruším aktuální kvíz?

hru lze zahájit bez vybraných kritérii, pak se do api neposílá ani id kategorie ani obtížnost a api pošle výběr ze všech kategorií i obtížností
zastavení kvízu zatím není možné

2024-01-12 15:34 UTC, nvbach91 approved these changes

2024-01-12 15:34 UTC, merged