pist02-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #238
Opened 2024-01-11 10:35 UTC by tomaspiskule

link: https://eso.vse.cz/~pist02/sp2/

2024-01-11 17:02 UTC, nvbach91 requested changes
- naimplementujte např.:
  - ukládání oblíbených filmů do localStorage a jejich zobrazení
  - vlastní hodnocení filmů v localStorage
  - možnost řazení nalezených výsledků podle např. názvu abecedně, hodnocení, rok vydání, ...

2024-01-11 17:02 UTC, nvbach91 commented on www/pist02/sp2/scripts/index.js
> +        document.getElementById('movie-list').style.backgroundColor = 'beige';
chybi omezeni opakovani odesilani pozadavku

2024-01-16 20:19 UTC, tomaspiskule commented
Pushnul jsem pres github desktop opravenou verzi + nahral na eso https://eso.vse.cz/~pist02/sp2/

pridane funkce aplikace:
1. ukládání oblíbených filmů do localStorage a jejich zobrazení
2. vlastní hodnocení filmů v localStorage
3. možnost řazení nalezených výsledků podle názvu abecedně, hodnocení, rok vydání - vše vzestupně i sestupně

Opravy:
1. Details vypsání nastylováno
2. DOM traversal pouzito
3. pouzito browser api - localstorage
4. <form> pouzito
5. vstup osetren
6. loading spinner pridan
7. pridano omezeni pro form submission i spamovani search buttonu

+ několik drobných kosmetickych uprav a stylovani

2024-01-18 21:29 UTC, nvbach91 requested changes

2024-01-18 21:29 UTC, nvbach91 commented on www/pist02/sp2/scripts/index.js
> +                        var detailsTopPosition = $detailsElement.offset().top - $columnsContainer.offset().top; //postion
undefined

2024-01-18 21:29 UTC, nvbach91 commented on www/pist02/sp2/scripts/index.js
> +                    var posterImageUrl = `https://image.tmdb.org/t/p/w500${movieDetails.poster_path}`;
poster_path muze byt null

2024-01-19 21:14 UTC, nvbach91 approved these changes

2024-01-19 21:14 UTC, merged