zabv04-sp2
nvbach91/4IZ268-2023-2024-ZS pull request #287
Opened 2024-01-31 22:48 UTC by vladik2288

Link to application: https://file-manager-412519.lm.r.appspot.com

Použil jsem jiný hosting servis pro aplikaci.

2024-02-01 12:42 UTC, nvbach91 requested changes
- chybi prace s Browser API
- aplikace nekomunikuje primo s Google Drive API, ale pres vlastni backend, proto chybi prihlaseni uzivatele - soubory se nenahravaji do drive uzivatele, ale do ciziho drive

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +    mainContainer.append(frameContainer);
opakovani zasahu do DOM

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +            uploadFilesNamesList.append($('<li>').text(file.name));
zasah do DOM v cyklu

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/css/style.css
> +.file-name {
opravit pretekani layoutu

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +async function showExistingFiles() {
pridat tlacitko update list

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +    $(".overlay").fadeIn(300); // Enable spinner
opakovane selektovani elementu

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +    $(".overlay").fadeOut(300); // Disable spinner
opakovane selektovani elementu

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +async function saveFilesOnDrive(files) {
chybi kontrola unikatnosti souboru

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +}
chybi resetovani inputu

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +    // File item
po nahravani vice souboru se soubory neobjevi v seznamu

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +            fileElement.hide();
`detach()` > `hide/show` > `append() back`

2024-02-01 12:42 UTC, nvbach91 commented on www/zabv04/sp2/public/js/main.js
> +                b.swapWith(a); // swap elements
`detach()` > `sort` > `append() back`

2024-02-02 00:56 UTC, vladik2288 commented
Zapomněl jsem dodat, povedlo se mi hostnout aplikaci na serveru eso.vse.cz.

Tady je odkaz: https://eso.vse.cz/~zabv04/sp2/

2024-02-02 09:32 UTC, vladik2288 commented on www/zabv04/sp2/public/js/main.js
> +    mainContainer.append(frameContainer);
detach nebo vytvorit novy element fragment

2024-02-02 09:32 UTC, vladik2288 commented on www/zabv04/sp2/public/js/main.js
> +            uploadFilesNamesList.append($('<li>').text(file.name));
v kazde iteraci se stranka prekresluje, opravit pomoci detach

2024-02-02 17:58 UTC, nvbach91 approved these changes

2024-02-02 17:58 UTC, merged