telo00-hw06
nvbach91/4IZ268-2023-2024-ZS pull request #43
Opened 2023-11-02 19:26 UTC by lesyabb2

odevzdavam hw06   + https://eso.vse.cz/~telo00/hw06/

2023-11-02 22:49 UTC, nvbach91 requested changes
neplatna struktura slozek v Pull Requestu

2023-11-03 11:54 UTC, lesyabb2 commented
> neplatna struktura slozek v Pull Requestu

snazila jsem to opravit. doufam ze uz je to dobre

2023-11-03 12:21 UTC, nvbach91 approved these changes

2023-11-03 12:21 UTC, nvbach91 commented on www/telo00/hw06/index.html
> +        <button id="task-3">Uloha 3 (Calculate Rectangle Area)</button>
nepouzivame inline js.

2023-11-03 12:21 UTC, merged